version: '3.2'
services:
  prudence:
    image: parvezyellow/prudence
    ports:
      - 3000:3000
    container_name: prudence
  jenkins:
    image: parvezyellow/jenkins
    user: root
    ports:
      - 3006:8080
      - 3007:50000
    volumes:
      - ~/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prudence
