apiVersion: v1
kind: Service
metadata:
  name: kube-redis-0
  namespace: redis
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
          statefulset.kubernetes.io/pod-name: redis-cluster-0
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kube-redis-1
  namespace: redis
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
          statefulset.kubernetes.io/pod-name: redis-cluster-1
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kube-redis-2
  namespace: redis
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
          statefulset.kubernetes.io/pod-name: redis-cluster-2
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kube-redis-3
  namespace: redis
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
          statefulset.kubernetes.io/pod-name: redis-cluster-3
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kube-redis-4
  namespace: redis
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
          statefulset.kubernetes.io/pod-name: redis-cluster-4
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kube-redis-5
  namespace: redis
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
          statefulset.kubernetes.io/pod-name: redis-cluster-5
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
